env: prod
component: shipping

params: "CART_ENDPOINT:prod.shipping.cart_endpoint,DB_HOST:prod.rds.endpoint"

schemaLoadJob:
  create: true
  type: mysql

resources:
limits:
  cpu: 1000m
  memory: 1024Mi
requests:
  cpu: 1000m
  memory: 1500Mi